# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://conda.anaconda.org/esri/win-64/arcgis-1.8.0-py36_1092.tar.bz2
https://conda.anaconda.org/esri/win-64/arcgispro-2.5-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/asn1crypto-0.24.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/atomicwrites-1.3.0-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/attrs-19.1.0-py36_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/backcall-0.1.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/blas-1.0-mkl.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/bleach-3.1.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/blinker-1.4-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ca-certificates-2019.8.28-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/certifi-2019.9.11-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/cffi-1.12.3-py36h7a1dbc1_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/cftime-1.0.0b1-py36h452e1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/chardet-3.0.4-py36_1003.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/colorama-0.4.1-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/cryptography-2.7-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/cycler-0.10.0-py36h009560c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/decorator-4.4.0-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/defusedxml-0.6.0-py_0.tar.bz2
https://conda.anaconda.org/esri/win-64/despatch-0.1.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/entrypoints-0.3-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/et_xmlfile-1.0.1-py36h3d2d736_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/fastcache-1.1.0-py36he774522_0.tar.bz2
https://conda.anaconda.org/esri/win-64/freetype-2.9.1-vc14_0.tar.bz2
https://conda.anaconda.org/esri/win-64/future-0.17.1-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/gdal-2.3.3-arcgispro_11.tar.bz2
https://conda.anaconda.org/esri/win-64/h5py-2.9.0-py36_arcgispro_2.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/html5lib-1.0.1-py_0.tar.bz2
https://conda.anaconda.org/esri/win-64/icc_rt-2019.0.4-arcgispro_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/idna-2.8-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/importlib_metadata-0.19-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/intel-openmp-2019.4-arcgispro_245.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ipykernel-5.1.2-py36h39e3cac_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ipython-7.8.0-py36h39e3cac_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/ipython_genutils-0.2.0-py36h3c5d0ee_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/ipywidgets-7.5.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/jdcal-1.4.1-py_0.tar.bz2
https://conda.anaconda.org/esri/win-64/jedi-0.15.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jinja2-2.10.1-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/json5-0.8.5-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jsonschema-3.0.2-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/jupyter_client-5.3.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jupyter_console-6.0.0-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/jupyter_core-4.5.0-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/jupyterlab-1.1.4-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_server-1.0.6-py_0.tar.bz2
https://conda.anaconda.org/esri/win-64/keyring-19.0.2-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/kiwisolver-1.1.0-py36ha925a31_0.tar.bz2
https://conda.anaconda.org/esri/win-64/lerc-0.1.0-py36h39e3cac_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libpng-1.6.37-h2a8f88b_0.tar.bz2
https://conda.anaconda.org/esri/win-64/libsodium-1.0.18-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/markupsafe-1.1.1-py36he774522_0.tar.bz2
https://conda.anaconda.org/esri/win-64/matplotlib-3.1.1-py36_0e.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mistune-0.8.4-py36he774522_0.tar.bz2
https://conda.anaconda.org/esri/win-64/mkl-2019.4-arcgispro_245.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl-service-2.3.0-py36hb782905_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl_fft-1.0.14-py36h14836fe_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl_random-1.0.2-py36h343c172_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/more-itertools-7.2.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mpmath-1.1.0-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/nbconvert-5.5.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/nbformat-4.4.0-py36h3a5bc1b_0.tar.bz2
https://conda.anaconda.org/esri/win-64/netcdf4-1.5.1.2-py36_arcgispro_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/nose-1.3.7-py36_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/notebook-6.0.1-py36_0.tar.bz2
https://conda.anaconda.org/esri/noarch/ntlm-auth-1.4.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numexpr-2.7.0-py36hdce8814_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-1.16.5-py36h19fb1c0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-base-1.16.5-py36hc3f5095_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/oauthlib-3.1.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/openpyxl-2.6.2-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/openssl-1.1.1d-he774522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/packaging-19.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pandas-0.25.1-py36ha925a31_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/pandocfilters-1.4.2-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/parso-0.5.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pickleshare-0.7.5-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pip-19.2.3-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pluggy-0.12.0-py_0.tar.bz2
https://conda.anaconda.org/esri/win-64/pro_notebook_integration-2.5-py36_5.tar.bz2
https://conda.anaconda.org/esri/win-64/prometheus_client-0.7.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/prompt_toolkit-2.0.9-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/psutil-5.6.3-py36he774522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/py-1.8.0-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/pybind11-2.3.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pycparser-2.19-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/pygments-2.4.2-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyjwt-1.7.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyopenssl-19.0.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.2-py_0.tar.bz2
https://conda.anaconda.org/esri/noarch/pypdf2-1.26.0-py_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyrsistent-0.14.11-py36he774522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pyshp-2.1.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pysocks-1.7.0-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/pytest-4.6.5-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/python-3.6.9-1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/python-dateutil-2.8.0-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/pytz-2019.2-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/pywin32-ctypes-0.2.0-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/pywinpty-0.5-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/pyzmq-18.1.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/requests-2.22.0-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/requests-kerberos-0.12.0-0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/requests-oauthlib-1.3.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/requests-toolbelt-0.9.1-py_0.tar.bz2
https://conda.anaconda.org/esri/noarch/requests_ntlm-1.1.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/scipy-1.3.1-py36h29ff71c_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/send2trash-1.5.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/setuptools-41.2.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/simplegeneric-0.8.1-py36_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/six-1.12.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/sqlite-3.29.0-he774522_0.tar.bz2
https://conda.anaconda.org/esri/win-64/sympy-1.4-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/terminado-0.8.2-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/testpath-0.4.2-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/tornado-6.0.3-py36he774522_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/traitlets-4.3.2-py36h096827d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/urllib3-1.24.2-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/vc-14.1-h0510ff6_4.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/vs2015_runtime-14.16.27012-hf0eaf9b_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/wcwidth-0.1.7-py36h3d5aa90_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/webencodings-0.5.1-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/wheel-0.33.6-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/widgetsnbextension-3.5.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/win_inet_pton-1.1.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/wincertstore-0.2-py36h7fe50ca_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/winkerberos-0.7.0-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/winpty-0.4.3-4.tar.bz2
https://conda.anaconda.org/esri/win-64/x86cpu-0.4-py36_1.tar.bz2
https://conda.anaconda.org/esri/win-64/xeus-0.23.2-2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/xlrd-1.2.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/xlwt-1.3.0-py36h1a4751e_0.tar.bz2
https://conda.anaconda.org/esri/win-64/zeromq-4.3.2-0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/zipp-0.5.2-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/zlib-1.2.11-h62dcd97_3.tar.bz2
